### ISSUE TITLE
worker may crash after gzip decompress error

### ISSUE THREAD

**Issue by Ghost-chu** [bitdruid/python-wayback-machine-downloader#5] opened 2024-06-04 05:17 UTC
Sometimes Wayback Machine may returns a page with gzipped but the stream may ended before EOF. In this case, the worker may crashed and never restart during downloading.

**Comment by bitdruid** [comment] 2024-06-07 21:50
i think this issue also resolved with #4 - but i couldn't reproduce it. i think the problem was somewhere else in the code

**Closed by bitdruid** 2024-06-07 21:50 UTC
Labels: bug
